openapi: 3.0.0
info:
  title: HackMD Open History API
  version: 1.0.0
  description: HackMD OpenAPI
  license:
    name: UNLICENSED
  contact:
    name: HackMD Team
    email: support@hackmd.io
servers:
- url: /v1
  description: API Server
tags:
- name: History
  description: Operations related to user's note history.
paths:
  /history:
    get:
      operationId: GetHistory
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                items: {}
                type: array
      description: Get note history for the current user
      tags:
      - History
      security:
      - token: []
      parameters:
      - description: The maximum number of history items to return.
        in: query
        name: limit
        required: false
        schema:
          format: double
          type: number
components:
  securitySchemes:
    token:
      type: http
      scheme: bearer
